site_name: Openfisca Working Group
site_url: https://benjello.github.io/openfisca-technical-committee


extra:
  social:
    - icon: https://avatars.githubusercontent.com/u/1794404?s=400&u=4996ebc5bad636562d1c1cbaca2f30d93dbcfb82&v=4
      link: https://github.com/openfisca
      name: Openfisca

theme:
  name: material
  logo: https://avatars.githubusercontent.com/u/1794404?s=400&u=4996ebc5bad636562d1c1cbaca2f30d93dbcfb82&v=4
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - Home: index.md
  - About: about.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
