site_name: Openfisca Working Group
site_url: https://benjello.github.io/openfisca-technical-committee
repo_url: https://github.com/benjello/openfisca-technical-committee
repo_name: benjello/openfisca-technical-committee
site_description: |
  OpenFisca Working Group is a collaborative space for the OpenFisca community to discuss technical matters, share knowledge, and improve the platform.

theme:
  name: material
  logo: https://avatars.githubusercontent.com/u/1794404
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view

edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - About: about.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
