[project]
name = "openfisca-technical-committee"
version = "0.1.0"
description = "Openisca Working Group"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
]

# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"
